### ISSUE TITLE
Why has this library been forked?

### ISSUE THREAD

**Issue by jordwalke** [rgrinberg/ocaml-hamt#2]
Refering to: https://github.com/thizanne/ocaml-hamt/commits/master

**Comment by rgrinberg** [comment]
The original author did not bother to package this library up and put it up on opam so I asked if I could do it for him (and move it to github in the process as well) and he was okay with it. Looks like he ended up moving to github as well. Probably because gitorious is closing. Probably there's no reason for this "fork" to exist really but it's only a fork technically. The code is still exactly the same.

**Comment by jordwalke** [comment]
It looks like it has some changes that aren't reflected here

**Comment by rgrinberg** [comment]
I've had another (brief) look and I disagree. This is the last commit that I have

https://github.com/rgrinberg/ocaml-hamt/commit/8708e4b561b8978e1436ea6de78f0fe995ee8252

It seem to be the last commit which made a change to the actual code itself.

**Comment by jordwalke** [comment]
Ah yes, it looks like the changes I saw were not related to the code.

**Comment by Leonidas-from-XIV** [comment]
@thizanne Maybe we could somehow join efforts? It would be a shame to have this effort go to waste.

**Comment by thizanne** [comment]
It seems nobody (me first) has doing a lot of effort on this recently (and by recently I mean "for the last 4 years"). However, the library should be mostly usable, at least for experimenting.

That being said, I'm not against merging the two repos if it helps not-fragmenting the (very low) contribution activity.

**Comment by rgrinberg** [comment]
> That being said, I'm not against merging the two repos if it helps not-fragmenting the (very low) contribution activity.

Sounds good to me. I can archive this repository once me and @Leonidas-from-XIV are contributors to your repository.

**Comment by thizanne** [comment]
I added both of you. Your packaging-related changes should be merged, do you agree to do it? It's probably safer than me, since you authored them. Obviously feel free to aggressively resolve any potential conflict in your favor.

**Comment by Leonidas-from-XIV** [comment]
> do you agree to do it?

Yes, I can do it. I'll redo that PR on top of your repo.
